# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ntity.proto\"l\n\x06\x45ntity\x12\x12\n\ninServerId\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x16\n\x0e\x61nimationIndex\x18\x04 \x01(\r\x12\r\n\x05state\x18\x05 \x01(\r\x12\x11\n\tdirection\x18\x06 \x01(\r\"%\n\x08\x45ntities\x12\x19\n\x08\x65ntities\x18\x01 \x03(\x0b\x32\x07.EntityB\nZ\x08./protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\010./protos'
  _globals['_ENTITY']._serialized_start=16
  _globals['_ENTITY']._serialized_end=124
  _globals['_ENTITIES']._serialized_start=126
  _globals['_ENTITIES']._serialized_end=163
# @@protoc_insertion_point(module_scope)
